### ISSUE TITLE
Image thumbnailing test failures

### ISSUE THREAD

**Issue by mithrandi** [twisted/mantissa#11]
I have absolutely no clue whatsoever about what is happening here, or what this test is testing.

```
[FAIL]
Traceback (most recent call last):
  File "/home/mithrandi/code/Mantissa/xmantissa/test/test_people.py", line 289, in test_makeThumbnail116
    self.assertEqual(extrema, (0, 119), cause)
  File "/home/mithrandi/deployment/virtualenvs/Mantissa/local/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 447, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: Image.new('RGBA', (30, 120)) via PNG
not equal:
a = (0, 255)
b = (0, 119)
```

**Comment by glyph** [comment]
This test is trying to say something way too nuanced about the colors of the thumbnailed image, and failing to express itself well.  It's just testing PIL itself, basically.  I think the right solution is to delete the test, since "a thumbnail of the appropriate size is produced" is tested adequately elsewhere.
